[package]
name = "wavebreak"
version = "0.1.0"
authors = ["Zeno <zeno@oxydyze.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.18"
rand = "0.7"
specs = "0.16"
specs-derive = "0.4"
